/* Siege Operator Quiz — guess the operator from the icon.
 * Reads window.OPERATORS from manifest.js (generated by gen_manifest.py).
 * Each operator: { file: "<name>.png", name: "<Display Name>" }.
 */
(function () {
  "use strict";

  var OPS = (window.OPERATORS || []).slice();
  if (!OPS.length) {
    document.getElementById("grid").textContent =
      "No operators found — run gen_manifest.py to build manifest.js.";
    return;
  }

  var TOTAL = OPS.length;
  // All correct names, sorted, for the dropdowns and word bank.
  var NAMES = OPS.map(function (o) { return o.name; }).sort(function (a, b) {
    return a.localeCompare(b);
  });

  // DOM refs
  var gridEl = document.getElementById("grid");
  var bankEl = document.getElementById("bank");
  var statusEl = document.getElementById("status");
  var resultEl = document.getElementById("result");
  var submitBtn = document.getElementById("submitBtn");
  var resetBtn = document.getElementById("resetBtn");
  var againBtn = document.getElementById("againBtn");

  // Game state
  var order = [];            // shuffled OPS entries, one per cell
  var assignment = [];       // assignment[i] = name string or null
  var selectedName = null;   // currently picked word-bank name (click-to-assign)
  var submitted = false;

  function shuffle(arr) {
    for (var i = arr.length - 1; i > 0; i--) {
      var j = Math.floor(Math.random() * (i + 1));
      var t = arr[i]; arr[i] = arr[j]; arr[j] = t;
    }
    return arr;
  }

  function imgSrc(file) {
    // Encode each path segment so spaces/accents in filenames stay valid.
    return "icons/" + encodeURIComponent(file);
  }

  // ---- Rendering -----------------------------------------------------------

  function buildBank() {
    bankEl.innerHTML = "";
    NAMES.forEach(function (name) {
      var chip = document.createElement("button");
      chip.type = "button";
      chip.className = "chip";
      chip.textContent = name;
      chip.dataset.name = name;
      chip.addEventListener("click", function () {
        if (submitted) return;
        if (selectedName === name) {
          selectedName = null;       // toggle off
        } else {
          selectedName = name;
        }
        refresh();
      });
      bankEl.appendChild(chip);
    });
  }

  function makeSelect(cellIndex) {
    var sel = document.createElement("select");
    var blank = document.createElement("option");
    blank.value = "";
    blank.textContent = "— pick —";
    sel.appendChild(blank);
    NAMES.forEach(function (name) {
      var opt = document.createElement("option");
      opt.value = name;
      opt.textContent = name;
      sel.appendChild(opt);
    });
    sel.addEventListener("change", function () {
      if (submitted) return;
      assignment[cellIndex] = sel.value || null;
      selectedName = null;
      refresh();
    });
    return sel;
  }

  function buildGrid() {
    gridEl.innerHTML = "";
    order.forEach(function (op, i) {
      var cell = document.createElement("div");
      cell.className = "cell";
      cell.dataset.index = i;

      var img = document.createElement("img");
      img.src = imgSrc(op.file);
      img.alt = "Operator icon";
      img.loading = "lazy";

      var sel = makeSelect(i);

      var reveal = document.createElement("div");
      reveal.className = "reveal";

      cell.appendChild(img);
      cell.appendChild(sel);
      cell.appendChild(reveal);

      cell.addEventListener("click", function (e) {
        if (submitted) return;
        if (e.target.tagName === "SELECT") return; // let dropdown handle itself
        if (selectedName) {
          assignment[i] = selectedName;
          selectedName = null;
          refresh();
        } else if (assignment[i]) {
          // No name picked: clicking an assigned cell clears it.
          assignment[i] = null;
          refresh();
        }
      });

      gridEl.appendChild(cell);
    });
  }

  // ---- State sync ----------------------------------------------------------

  function duplicateNames() {
    var counts = {};
    assignment.forEach(function (n) {
      if (n) counts[n] = (counts[n] || 0) + 1;
    });
    var dups = {};
    Object.keys(counts).forEach(function (n) {
      if (counts[n] > 1) dups[n] = counts[n];
    });
    return dups;
  }

  function refresh() {
    if (submitted) return;
    var dups = duplicateNames();
    var dupNames = Object.keys(dups);
    var assignedCount = assignment.filter(Boolean).length;

    // Update chips (used / selected state).
    Array.prototype.forEach.call(bankEl.children, function (chip) {
      var name = chip.dataset.name;
      var inUse = assignment.indexOf(name) !== -1;
      chip.classList.toggle("used", inUse);
      chip.classList.toggle("selected", selectedName === name);
    });

    // Update each cell + its dropdown.
    Array.prototype.forEach.call(gridEl.children, function (cell, i) {
      var name = assignment[i] || "";
      var sel = cell.querySelector("select");
      if (sel.value !== name) sel.value = name;
      sel.classList.toggle("has-value", !!name);
      cell.classList.toggle("assigned", !!name);
      cell.classList.toggle("dup", !!name && dups[name] > 0);
      cell.classList.toggle("targetable", !!selectedName || !!name);
    });

    // Status + submit gating.
    if (dupNames.length) {
      statusEl.className = "status warn";
      statusEl.textContent =
        "Duplicate: " + dupNames.join(", ") + " — each name once";
      submitBtn.disabled = true;
    } else if (assignedCount < TOTAL) {
      statusEl.className = "status";
      statusEl.textContent = assignedCount + " / " + TOTAL + " assigned";
      submitBtn.disabled = true;
    } else {
      statusEl.className = "status ready";
      statusEl.textContent = "All assigned — ready to submit!";
      submitBtn.disabled = false;
    }
  }

  // ---- Submit / reveal -----------------------------------------------------

  function onSubmit() {
    if (submitBtn.disabled) return;
    submitted = true;
    document.body.classList.add("locked");

    var score = 0;
    Array.prototype.forEach.call(gridEl.children, function (cell, i) {
      var guess = assignment[i];
      var correct = order[i].name;
      var sel = cell.querySelector("select");
      sel.disabled = true;
      cell.classList.remove("dup", "targetable");

      var reveal = cell.querySelector(".reveal");
      if (guess === correct) {
        score++;
        cell.classList.add("correct");
        reveal.className = "reveal good";
        reveal.textContent = "✓ " + correct;
      } else {
        cell.classList.add("incorrect");
        reveal.className = "reveal bad";
        reveal.textContent = "✗ " + correct;
      }
    });

    statusEl.className = "status ready";
    statusEl.textContent = "Done!";
    resultEl.textContent = "Score: " + score + " / " + TOTAL;
    submitBtn.classList.add("hidden");
    resetBtn.classList.add("hidden");
    againBtn.classList.remove("hidden");
  }

  // ---- New / reset ---------------------------------------------------------

  function newGame() {
    submitted = false;
    selectedName = null;
    document.body.classList.remove("locked");
    order = shuffle(OPS.slice());
    assignment = new Array(TOTAL).fill(null);
    resultEl.textContent = "";
    submitBtn.classList.remove("hidden");
    resetBtn.classList.remove("hidden");
    againBtn.classList.add("hidden");
    buildGrid();
    refresh();
  }

  function clearAll() {
    if (submitted) return;
    assignment = new Array(TOTAL).fill(null);
    selectedName = null;
    refresh();
  }

  submitBtn.addEventListener("click", onSubmit);
  resetBtn.addEventListener("click", clearAll);
  againBtn.addEventListener("click", newGame);

  buildBank();
  newGame();
})();
