#!/usr/bin/env python3
"""Scan the icons/ folder and generate manifest.js for the quiz.

GitHub Pages can't list a directory at runtime, so we bake the list of
icons (and their pretty, accented display names) into a JS file the game
reads. Display names come from operators.txt when a match exists, otherwise
we title-case the filename.

Run this whenever you add/remove icons:  python gen_manifest.py
"""
import json
import os
import unicodedata

HERE = os.path.dirname(os.path.abspath(__file__))
ICON_DIR = os.path.join(HERE, "icons")
NAMES_FILE = os.path.join(HERE, "operators.txt")
OUT_FILE = os.path.join(HERE, "manifest.js")

# Characters that NFKD doesn't decompose to ASCII but we want folded anyway.
SPECIAL = {"ø": "o", "Ø": "o", "ð": "d", "þ": "th", "ß": "ss"}


def fold(s: str) -> str:
    """Reduce a name to a lowercase alphanumeric key for matching."""
    s = "".join(SPECIAL.get(c, c) for c in s)
    s = unicodedata.normalize("NFKD", s).encode("ascii", "ignore").decode()
    return "".join(c for c in s.lower() if c.isalnum())


def load_display_names() -> dict:
    """Map folded-key -> pretty display name from operators.txt."""
    names = {}
    if os.path.exists(NAMES_FILE):
        with open(NAMES_FILE, encoding="utf-8") as f:
            for line in f:
                name = line.strip()
                if name:
                    names[fold(name)] = name
    return names


def main() -> None:
    display = load_display_names()
    entries = []
    for fn in sorted(os.listdir(ICON_DIR)):
        if not fn.lower().endswith(".png"):
            continue
        stem = os.path.splitext(fn)[0]
        pretty = display.get(fold(stem)) or stem.replace("_", " ").title()
        entries.append({"file": fn, "name": pretty})

    js = (
        "// AUTO-GENERATED by gen_manifest.py — do not edit by hand.\n"
        "// Each entry: { file: <icons/ filename>, name: <correct answer> }\n"
        "window.OPERATORS = " + json.dumps(entries, ensure_ascii=False, indent=2) + ";\n"
    )
    with open(OUT_FILE, "w", encoding="utf-8") as f:
        f.write(js)
    print(f"Wrote {OUT_FILE} with {len(entries)} operators.")


if __name__ == "__main__":
    main()
