// AUTO-GENERATED by gen_manifest.py — do not edit by hand.
// Each entry: { file: <icons/ filename>, name: <correct answer> }
window.OPERATORS = [
  {
    "file": "ace.png",
    "name": "ACE"
  },
  {
    "file": "alibi.png",
    "name": "ALIBI"
  },
  {
    "file": "amaru.png",
    "name": "AMARU"
  },
  {
    "file": "aruni.png",
    "name": "ARUNI"
  },
  {
    "file": "ash.png",
    "name": "ASH"
  },
  {
    "file": "azami.png",
    "name": "AZAMI"
  },
  {
    "file": "bandit.png",
    "name": "BANDIT"
  },
  {
    "file": "blackbeard.png",
    "name": "BLACKBEARD"
  },
  {
    "file": "blitz.png",
    "name": "BLITZ"
  },
  {
    "file": "brava.png",
    "name": "BRAVA"
  },
  {
    "file": "buck.png",
    "name": "BUCK"
  },
  {
    "file": "capitao.png",
    "name": "CAPITÃO"
  },
  {
    "file": "castle.png",
    "name": "CASTLE"
  },
  {
    "file": "caveira.png",
    "name": "CAVEIRA"
  },
  {
    "file": "clash.png",
    "name": "CLASH"
  },
  {
    "file": "deimos.png",
    "name": "DEIMOS"
  },
  {
    "file": "denari.png",
    "name": "DENARI"
  },
  {
    "file": "doc.png",
    "name": "DOC"
  },
  {
    "file": "dokkaebi.png",
    "name": "DOKKAEBI"
  },
  {
    "file": "echo.png",
    "name": "ECHO"
  },
  {
    "file": "ela.png",
    "name": "ELA"
  },
  {
    "file": "fenrir.png",
    "name": "FENRIR"
  },
  {
    "file": "finka.png",
    "name": "FINKA"
  },
  {
    "file": "flores.png",
    "name": "FLORES"
  },
  {
    "file": "frost.png",
    "name": "FROST"
  },
  {
    "file": "fuze.png",
    "name": "FUZE"
  },
  {
    "file": "glaz.png",
    "name": "GLAZ"
  },
  {
    "file": "goyo.png",
    "name": "GOYO"
  },
  {
    "file": "gridlock.png",
    "name": "GRIDLOCK"
  },
  {
    "file": "grim.png",
    "name": "GRIM"
  },
  {
    "file": "hibana.png",
    "name": "HIBANA"
  },
  {
    "file": "iana.png",
    "name": "IANA"
  },
  {
    "file": "iq.png",
    "name": "IQ"
  },
  {
    "file": "jackal.png",
    "name": "JACKAL"
  },
  {
    "file": "jager.png",
    "name": "JÄGER"
  },
  {
    "file": "kaid.png",
    "name": "KAID"
  },
  {
    "file": "kali.png",
    "name": "KALI"
  },
  {
    "file": "kapkan.png",
    "name": "KAPKAN"
  },
  {
    "file": "lesion.png",
    "name": "LESION"
  },
  {
    "file": "lion.png",
    "name": "LION"
  },
  {
    "file": "maestro.png",
    "name": "MAESTRO"
  },
  {
    "file": "maverick.png",
    "name": "MAVERICK"
  },
  {
    "file": "melusi.png",
    "name": "MELUSI"
  },
  {
    "file": "mira.png",
    "name": "MIRA"
  },
  {
    "file": "montagne.png",
    "name": "MONTAGNE"
  },
  {
    "file": "mozzie.png",
    "name": "MOZZIE"
  },
  {
    "file": "mute.png",
    "name": "MUTE"
  },
  {
    "file": "nokk.png",
    "name": "NØKK"
  },
  {
    "file": "nomad.png",
    "name": "NOMAD"
  },
  {
    "file": "oryx.png",
    "name": "ORYX"
  },
  {
    "file": "osa.png",
    "name": "OSA"
  },
  {
    "file": "pulse.png",
    "name": "PULSE"
  },
  {
    "file": "ram.png",
    "name": "RAM"
  },
  {
    "file": "rauora.png",
    "name": "RAUORA"
  },
  {
    "file": "rook.png",
    "name": "ROOK"
  },
  {
    "file": "sens.png",
    "name": "SENS"
  },
  {
    "file": "skopos.png",
    "name": "SKOPÓS"
  },
  {
    "file": "sledge.png",
    "name": "SLEDGE"
  },
  {
    "file": "smoke.png",
    "name": "SMOKE"
  },
  {
    "file": "solis.png",
    "name": "SOLIS"
  },
  {
    "file": "tachanka.png",
    "name": "TACHANKA"
  },
  {
    "file": "thatcher.png",
    "name": "THATCHER"
  },
  {
    "file": "thermite.png",
    "name": "THERMITE"
  },
  {
    "file": "thorn.png",
    "name": "THORN"
  },
  {
    "file": "thunderbird.png",
    "name": "THUNDERBIRD"
  },
  {
    "file": "tubarao.png",
    "name": "TUBARÃO"
  },
  {
    "file": "twitch.png",
    "name": "TWITCH"
  },
  {
    "file": "valkyrie.png",
    "name": "VALKYRIE"
  },
  {
    "file": "vigil.png",
    "name": "VIGIL"
  },
  {
    "file": "wamai.png",
    "name": "WAMAI"
  },
  {
    "file": "warden.png",
    "name": "WARDEN"
  },
  {
    "file": "ying.png",
    "name": "YING"
  },
  {
    "file": "zero.png",
    "name": "ZERO"
  },
  {
    "file": "zofia.png",
    "name": "ZOFIA"
  }
];
